const GET_DIETS ='GET_DIETS'
const POST_RECIPE ='POST_RECIPE'
const GET_ALL='GET_ALL'
const FILTER_DIETS = 'FILTER_DIETS'
const FILTER_BY_SOURCE = 'FILTER_BY_SOURCE'
const ORDER_BY_NAME ='ORDER_BY_NAME'
const ORDER_BY_HEALTHSCORE='ORDER_BY_HEALTHSCORE'
const GET_BY_NAME = 'GET_BY_NAME'
const GET_BY_ID   ='GET_BY_ID'
const CLEAN_DETAIL ='CLEAN_DETAIL'

export {GET_DIETS,POST_RECIPE,GET_ALL,FILTER_DIETS,FILTER_BY_SOURCE,ORDER_BY_NAME,ORDER_BY_HEALTHSCORE,GET_BY_NAME,GET_BY_ID,CLEAN_DETAIL}